# Generated by Django 5.2.4 on 2026-03-25 17:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("analytics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=200)),
                ("code", models.CharField(db_index=True, max_length=20, unique=True)),
                (
                    "region",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Broader region grouping.",
                        max_length=100,
                    ),
                ),
                (
                    "population",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Approximate population from latest census.",
                        null=True,
                    ),
                ),
                (
                    "area_sq_km",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Area in square kilometres.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "boundary_geojson",
                    models.JSONField(
                        help_text="GeoJSON Polygon or MultiPolygon of district boundary."
                    ),
                ),
                (
                    "center_lat",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Centre latitude for map positioning.",
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "center_lng",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Centre longitude for map positioning.",
                        max_digits=9,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "verbose_name": "District",
                "verbose_name_plural": "Districts",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CoverageUpload",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "technology",
                    models.CharField(
                        choices=[
                            ("2G", "2G"),
                            ("3G", "3G"),
                            ("4G", "4G"),
                            ("5G", "5G"),
                        ],
                        max_length=5,
                    ),
                ),
                ("file", models.FileField(upload_to="coverages/uploads/%Y/%m/")),
                ("file_name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        default=0, help_text="File size in bytes."
                    ),
                ),
                (
                    "period",
                    models.DateField(help_text="Reporting period this upload covers."),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "records_created",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of CoverageArea records created from this upload.",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Error details if processing failed.",
                    ),
                ),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coverage_uploads",
                        to="analytics.networkoperator",
                    ),
                ),
            ],
            options={
                "verbose_name": "Coverage Upload",
                "verbose_name_plural": "Coverage Uploads",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CoverageArea",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "technology",
                    models.CharField(
                        choices=[
                            ("2G", "2G"),
                            ("3G", "3G"),
                            ("4G", "4G"),
                            ("5G", "5G"),
                        ],
                        db_index=True,
                        max_length=5,
                    ),
                ),
                (
                    "coverage_level",
                    models.CharField(
                        choices=[
                            ("FULL", "Full (80-100%)"),
                            ("PARTIAL", "Partial (30-79%)"),
                            ("MINIMAL", "Minimal (1-29%)"),
                            ("NONE", "None (0%)"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                (
                    "coverage_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Numeric coverage percentage (0-100).",
                        max_digits=5,
                    ),
                ),
                (
                    "population_covered",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Estimated population with access.",
                        null=True,
                    ),
                ),
                (
                    "geometry_geojson",
                    models.JSONField(
                        blank=True,
                        help_text="Coverage polygon GeoJSON (if different from full district boundary).",
                        null=True,
                    ),
                ),
                (
                    "signal_strength_avg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Average signal strength in dBm.",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "period",
                    models.DateField(
                        db_index=True,
                        help_text="Reporting period (first day of quarter).",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("BOCRA", "BOCRA Internal Data"),
                            ("OPERATOR_SUBMISSION", "Operator Submission"),
                            ("ESTIMATED", "Estimated / Extrapolated"),
                        ],
                        default="BOCRA",
                        max_length=25,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coverage_areas",
                        to="analytics.networkoperator",
                    ),
                ),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coverage_areas",
                        to="coverages.district",
                    ),
                ),
            ],
            options={
                "verbose_name": "Coverage Area",
                "verbose_name_plural": "Coverage Areas",
                "ordering": ["-period", "operator__name", "district__name"],
                "unique_together": {("operator", "district", "technology", "period")},
            },
        ),
    ]
