# Generated by Django 5.2.4 on 2026-03-21 20:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NetworkOperator",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=200)),
                ("code", models.CharField(db_index=True, max_length=20, unique=True)),
                (
                    "logo",
                    models.FileField(
                        blank=True, null=True, upload_to="analytics/logos/"
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "verbose_name": "Network Operator",
                "verbose_name_plural": "Network Operators",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="QoSRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "period",
                    models.DateField(db_index=True, help_text="Reporting period."),
                ),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("CALL_SUCCESS", "Call Success Rate"),
                            ("DATA_SPEED", "Data Speed"),
                            ("LATENCY", "Latency"),
                            ("DROP_RATE", "Drop Rate"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("value", models.DecimalField(decimal_places=4, max_digits=10)),
                (
                    "unit",
                    models.CharField(
                        help_text="Unit of measurement (%, Mbps, ms, etc.)",
                        max_length=20,
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Geographic region (optional).",
                        max_length=100,
                    ),
                ),
                (
                    "benchmark",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="BOCRA benchmark/target for this metric.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qos_records",
                        to="analytics.networkoperator",
                    ),
                ),
            ],
            options={
                "verbose_name": "QoS Record",
                "verbose_name_plural": "QoS Records",
                "ordering": ["-period", "operator__name"],
            },
        ),
        migrations.CreateModel(
            name="TelecomsStat",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "period",
                    models.DateField(
                        db_index=True,
                        help_text="Reporting period (first day of month).",
                    ),
                ),
                (
                    "technology",
                    models.CharField(
                        choices=[
                            ("2G", "2G"),
                            ("3G", "3G"),
                            ("4G", "4G"),
                            ("5G", "5G"),
                        ],
                        db_index=True,
                        max_length=5,
                    ),
                ),
                ("subscriber_count", models.PositiveIntegerField(default=0)),
                (
                    "market_share_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "revenue",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Revenue in BWP (optional).",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to="analytics.networkoperator",
                    ),
                ),
            ],
            options={
                "verbose_name": "Telecoms Statistic",
                "verbose_name_plural": "Telecoms Statistics",
                "ordering": ["-period", "operator__name"],
                "unique_together": {("operator", "period", "technology")},
            },
        ),
    ]
