# Generated by Django 6.0.3 on 2026-03-27 05:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reference_number",
                    models.CharField(
                        blank=True, db_index=True, max_length=50, unique=True
                    ),
                ),
                ("requester_name", models.CharField(max_length=200)),
                ("requester_email", models.EmailField(max_length=254)),
                (
                    "requester_phone",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("organization", models.CharField(max_length=255)),
                (
                    "audit_type",
                    models.CharField(
                        choices=[
                            ("VULNERABILITY_ASSESSMENT", "Vulnerability Assessment"),
                            ("PENETRATION_TEST", "Penetration Test"),
                            ("COMPLIANCE_AUDIT", "Compliance Audit"),
                            ("INCIDENT_RESPONSE", "Incident Response"),
                            ("GENERAL", "General Inquiry"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Description of the system/service to be audited and specific concerns."
                    ),
                ),
                (
                    "preferred_date",
                    models.DateField(
                        blank=True,
                        help_text="Preferred start date for the audit.",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUBMITTED", "Submitted"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("SCHEDULED", "Scheduled"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("REJECTED", "Rejected"),
                        ],
                        db_index=True,
                        default="SUBMITTED",
                        max_length=20,
                    ),
                ),
                (
                    "staff_notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Internal notes from staff processing the request.",
                    ),
                ),
                (
                    "resolution",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Formal resolution or outcome.",
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_audits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null for anonymous requests.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Request",
                "verbose_name_plural": "Audit Requests",
                "ordering": ["-created_at"],
            },
        ),
    ]
