# Generated by Django 5.2.4 on 2026-03-24 21:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licensing", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="licencetype",
            options={
                "ordering": ["sort_order", "name"],
                "verbose_name": "Licence Type",
                "verbose_name_plural": "Licence Types",
            },
        ),
        migrations.AddField(
            model_name="licencetype",
            name="annual_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Recurring annual fee in BWP.",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="licencetype",
            name="eligibility_criteria",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Who is eligible to apply for this licence type.",
            ),
        ),
        migrations.AddField(
            model_name="licencetype",
            name="is_domain_applicable",
            field=models.BooleanField(
                default=False,
                help_text="If true, this licence is relevant when applying for .bw domains.",
            ),
        ),
        migrations.AddField(
            model_name="licencetype",
            name="renewal_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Renewal fee in BWP (may differ from initial fee).",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="licencetype",
            name="required_documents",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Structured list of required docs, e.g. [{"name": "Certificate of Incorporation", "required": true}].',
            ),
        ),
        migrations.AddField(
            model_name="licencetype",
            name="sort_order",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Display ordering within its sector (lower = first).",
            ),
        ),
        migrations.AlterField(
            model_name="licencetype",
            name="fee_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Initial application / licensing fee in BWP.",
                max_digits=12,
            ),
        ),
        migrations.CreateModel(
            name="LicenceSector",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(db_index=True, max_length=20, unique=True)),
                (
                    "description",
                    models.TextField(
                        help_text="Public-facing description of this regulatory sector."
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional icon identifier for the frontend.",
                        max_length=50,
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Display ordering (lower = first)."
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Only active sectors appear on the public portal.",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Licence Sector",
                "verbose_name_plural": "Licence Sectors",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.AddField(
            model_name="licencetype",
            name="sector",
            field=models.ForeignKey(
                blank=True,
                help_text="Regulatory sector this licence type belongs to.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="licence_types",
                to="licensing.licencesector",
            ),
        ),
    ]
