# Generated by Django 5.2.4 on 2026-03-24 20:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DomainApplication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reference_number",
                    models.CharField(
                        blank=True, db_index=True, max_length=30, unique=True
                    ),
                ),
                (
                    "application_type",
                    models.CharField(
                        choices=[
                            ("REGISTRATION", "Registration"),
                            ("RENEWAL", "Renewal"),
                            ("TRANSFER", "Transfer"),
                        ],
                        default="REGISTRATION",
                        max_length=20,
                    ),
                ),
                (
                    "domain_name",
                    models.CharField(
                        help_text="Requested FQDN (e.g., mycompany.co.bw)",
                        max_length=253,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("INFO_REQUESTED", "Additional Information Requested"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("registration_period_years", models.PositiveIntegerField(default=1)),
                ("organisation_name", models.CharField(max_length=300)),
                (
                    "organisation_registration_number",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("registrant_name", models.CharField(max_length=200)),
                ("registrant_email", models.EmailField(max_length=254)),
                (
                    "registrant_phone",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                ("registrant_address", models.TextField(blank=True, default="")),
                (
                    "nameserver_1",
                    models.CharField(blank=True, default="", max_length=253),
                ),
                (
                    "nameserver_2",
                    models.CharField(blank=True, default="", max_length=253),
                ),
                (
                    "nameserver_3",
                    models.CharField(blank=True, default="", max_length=253),
                ),
                (
                    "nameserver_4",
                    models.CharField(blank=True, default="", max_length=253),
                ),
                (
                    "tech_contact_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "tech_contact_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                (
                    "transfer_from_registrant",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "transfer_auth_code",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "justification",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Why the applicant wants this domain.",
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("decision_date", models.DateTimeField(blank=True, null=True)),
                ("decision_reason", models.TextField(blank=True, default="")),
                ("info_request_message", models.TextField(blank=True, default="")),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="domain_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="domain_applications_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="domain_applications_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_domain_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Domain Application",
                "verbose_name_plural": "Domain Applications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "domain_name",
                    models.CharField(db_index=True, max_length=253, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("EXPIRED", "Expired"),
                            ("SUSPENDED", "Suspended"),
                            ("PENDING_DELETE", "Pending Delete"),
                            ("DELETED", "Deleted"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("registrant_name", models.CharField(max_length=200)),
                ("registrant_email", models.EmailField(max_length=254)),
                (
                    "registrant_phone",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                ("registrant_address", models.TextField(blank=True, default="")),
                (
                    "organisation_name",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                (
                    "nameserver_1",
                    models.CharField(blank=True, default="", max_length=253),
                ),
                (
                    "nameserver_2",
                    models.CharField(blank=True, default="", max_length=253),
                ),
                (
                    "nameserver_3",
                    models.CharField(blank=True, default="", max_length=253),
                ),
                (
                    "nameserver_4",
                    models.CharField(blank=True, default="", max_length=253),
                ),
                (
                    "tech_contact_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "tech_contact_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                (
                    "registered_at",
                    models.DateTimeField(help_text="Original registration date."),
                ),
                (
                    "expires_at",
                    models.DateTimeField(help_text="When the registration expires."),
                ),
                ("last_renewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "is_seeded",
                    models.BooleanField(
                        default=False,
                        help_text="Imported/seeded data, not from a real application.",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="domains_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="domains_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "registrant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Current owner (null for seeded externals).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registered_domains",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_from_application",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="domain",
                        to="domains.domainapplication",
                    ),
                ),
            ],
            options={
                "verbose_name": "Domain",
                "verbose_name_plural": "Domains",
                "ordering": ["domain_name"],
            },
        ),
        migrations.CreateModel(
            name="DomainApplicationDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(help_text="Document label.", max_length=200)),
                ("file", models.FileField(upload_to="domains/documents/%Y/%m/")),
                ("file_type", models.CharField(blank=True, default="", max_length=50)),
                (
                    "file_size",
                    models.PositiveIntegerField(default=0, help_text="Size in bytes."),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="domains.domainapplication",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_domain_docs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Domain Application Document",
                "verbose_name_plural": "Domain Application Documents",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DomainApplicationStatusLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "from_status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("INFO_REQUESTED", "Additional Information Requested"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("INFO_REQUESTED", "Additional Information Requested"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField(blank=True, default="")),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_logs",
                        to="domains.domainapplication",
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="domain_application_status_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Domain Application Status Log",
                "verbose_name_plural": "Domain Application Status Logs",
                "ordering": ["changed_at"],
            },
        ),
        migrations.CreateModel(
            name="DomainEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("REGISTERED", "Registered"),
                            ("RENEWED", "Renewed"),
                            ("TRANSFERRED", "Transferred"),
                            ("NS_UPDATED", "Nameservers Updated"),
                            ("CONTACT_UPDATED", "Contact Updated"),
                            ("SUSPENDED", "Suspended"),
                            ("UNSUSPENDED", "Unsuspended"),
                            ("EXPIRED", "Expired"),
                            ("DELETED", "Deleted"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Human-readable change description."),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Structured before/after data.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="domains.domain",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="domain_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Domain Event",
                "verbose_name_plural": "Domain Events",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DomainZone",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Zone name (e.g., .co.bw)", max_length=50
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Unique short code (e.g., CO_BW)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Shown to applicants — who this zone is for."
                    ),
                ),
                (
                    "registration_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Registration fee in BWP.",
                        max_digits=12,
                    ),
                ),
                (
                    "renewal_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Annual renewal fee in BWP.",
                        max_digits=12,
                    ),
                ),
                ("fee_currency", models.CharField(default="BWP", max_length=3)),
                ("min_registration_years", models.PositiveIntegerField(default=1)),
                ("max_registration_years", models.PositiveIntegerField(default=10)),
                (
                    "is_restricted",
                    models.BooleanField(
                        default=False,
                        help_text="Requires special eligibility (e.g., .gov.bw).",
                    ),
                ),
                (
                    "eligibility_criteria",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Requirements for restricted zones.",
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Domain Zone",
                "verbose_name_plural": "Domain Zones",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="domainapplication",
            name="zone",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="applications",
                to="domains.domainzone",
            ),
        ),
        migrations.AddField(
            model_name="domain",
            name="zone",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="domains",
                to="domains.domainzone",
            ),
        ),
    ]
