# Generated by Django 5.2.4 on 2026-03-24 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domains", "0001_initial"),
        ("licensing", "0002_alter_licencetype_options_licencetype_annual_fee_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="domainapplication",
            name="licence_type",
            field=models.ForeignKey(
                blank=True,
                help_text="The licence type relevant to this domain registration (auto-selected).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="domain_applications",
                to="licensing.licencetype",
            ),
        ),
    ]
