# Generated by Django 5.2.4 on 2026-03-25 18:43

import alerts.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=200)),
                ("code", models.CharField(db_index=True, max_length=50, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Icon identifier for frontend (e.g. 'bell', 'shield').",
                        max_length=50,
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=True, help_text="Visible to anonymous subscribers."
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this category accepts new subscriptions.",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Display ordering (lower = first)."
                    ),
                ),
            ],
            options={
                "verbose_name": "Alert Category",
                "verbose_name_plural": "Alert Categories",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="AlertSubscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "email",
                    models.EmailField(db_index=True, max_length=254, unique=True),
                ),
                (
                    "is_confirmed",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Email confirmed via double opt-in.",
                    ),
                ),
                (
                    "confirm_token",
                    models.CharField(
                        default=alerts.models._generate_token,
                        help_text="Token for email confirmation link.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "unsubscribe_token",
                    models.CharField(
                        default=alerts.models._generate_token,
                        help_text="Token for one-click unsubscribe link.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "operator_filter",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional operator code filter (e.g. MASCOM, ORANGE, BTCL).",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Master on/off switch for this subscription.",
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True,
                        related_name="subscriptions",
                        to="alerts.alertcategory",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Linked user account (if registered).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alert_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Alert Subscription",
                "verbose_name_plural": "Alert Subscriptions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AlertLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("subject", models.CharField(max_length=300)),
                (
                    "body_preview",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="First 500 characters of the email body.",
                        max_length=500,
                    ),
                ),
                (
                    "related_object_type",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Type of triggering object (e.g. 'publication', 'tender').",
                        max_length=50,
                    ),
                ),
                (
                    "related_object_id",
                    models.UUIDField(
                        blank=True,
                        help_text="UUID of the triggering object.",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SENT", "Sent"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Error details if delivery failed.",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert_logs",
                        to="alerts.alertcategory",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert_logs",
                        to="alerts.alertsubscription",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alert Log",
                "verbose_name_plural": "Alert Logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["category", "-created_at"],
                        name="alerts_aler_categor_eb7931_idx",
                    ),
                    models.Index(
                        fields=["subscription", "-created_at"],
                        name="alerts_aler_subscri_3a8740_idx",
                    ),
                ],
            },
        ),
    ]
