# Generated by Django 5.2.4 on 2026-03-24 00:57

import publications.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publication",
            name="file",
            field=models.FileField(
                blank=True,
                help_text="Primary document file (PDF, DOCX, XLSX).",
                upload_to=publications.models.publication_file_path,
            ),
        ),
    ]
