# Generated by Django 5.2.4 on 2026-03-21 20:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("licensing", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Complaint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reference_number",
                    models.CharField(
                        blank=True, db_index=True, max_length=50, unique=True
                    ),
                ),
                (
                    "complainant_name",
                    models.CharField(
                        help_text="Required for anonymous complaints.", max_length=200
                    ),
                ),
                (
                    "complainant_email",
                    models.EmailField(
                        help_text="Required — used for status notifications.",
                        max_length=254,
                    ),
                ),
                (
                    "complainant_phone",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "against_operator_name",
                    models.CharField(
                        help_text="Free-text operator name (always filled, even if licence linked).",
                        max_length=255,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("SERVICE_QUALITY", "Service Quality"),
                            ("BILLING", "Billing Dispute"),
                            ("COVERAGE", "Network Coverage"),
                            ("CONDUCT", "Operator Conduct"),
                            ("INTERNET", "Internet Services"),
                            ("BROADCASTING", "Broadcasting"),
                            ("POSTAL", "Postal Services"),
                            ("OTHER", "Other"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("subject", models.CharField(max_length=300)),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUBMITTED", "Submitted"),
                            ("ASSIGNED", "Assigned"),
                            ("INVESTIGATING", "Under Investigation"),
                            ("AWAITING_RESPONSE", "Awaiting Response"),
                            ("RESOLVED", "Resolved"),
                            ("CLOSED", "Closed"),
                            ("REOPENED", "Reopened"),
                        ],
                        db_index=True,
                        default="SUBMITTED",
                        max_length=25,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("URGENT", "Urgent"),
                        ],
                        db_index=True,
                        default="MEDIUM",
                        max_length=10,
                    ),
                ),
                (
                    "resolution",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Formal resolution text — filled when case is resolved.",
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "sla_deadline",
                    models.DateTimeField(
                        blank=True,
                        help_text="Auto-calculated from priority on submission.",
                        null=True,
                    ),
                ),
                (
                    "against_licensee",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to an active licence, if identifiable.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="complaints_against",
                        to="licensing.licence",
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_complaints",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "complainant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null for anonymous complaints.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="complaints",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Complaint",
                "verbose_name_plural": "Complaints",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CaseNote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("content", models.TextField()),
                (
                    "is_internal",
                    models.BooleanField(
                        default=True,
                        help_text="Internal notes are visible to BOCRA staff only.",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="complaint_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "complaint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="complaints.complaint",
                    ),
                ),
            ],
            options={
                "verbose_name": "Case Note",
                "verbose_name_plural": "Case Notes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ComplaintDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Descriptive label for the evidence.", max_length=255
                    ),
                ),
                ("file", models.FileField(upload_to="complaints/documents/%Y/%m/")),
                ("file_type", models.CharField(blank=True, default="", max_length=100)),
                (
                    "file_size",
                    models.PositiveIntegerField(default=0, help_text="Size in bytes."),
                ),
                (
                    "complaint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="complaints.complaint",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_complaint_docs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Complaint Document",
                "verbose_name_plural": "Complaint Documents",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ComplaintStatusLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "from_status",
                    models.CharField(
                        choices=[
                            ("SUBMITTED", "Submitted"),
                            ("ASSIGNED", "Assigned"),
                            ("INVESTIGATING", "Under Investigation"),
                            ("AWAITING_RESPONSE", "Awaiting Response"),
                            ("RESOLVED", "Resolved"),
                            ("CLOSED", "Closed"),
                            ("REOPENED", "Reopened"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("SUBMITTED", "Submitted"),
                            ("ASSIGNED", "Assigned"),
                            ("INVESTIGATING", "Under Investigation"),
                            ("AWAITING_RESPONSE", "Awaiting Response"),
                            ("RESOLVED", "Resolved"),
                            ("CLOSED", "Closed"),
                            ("REOPENED", "Reopened"),
                        ],
                        max_length=25,
                    ),
                ),
                ("reason", models.TextField(blank=True, default="")),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="complaint_status_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "complaint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_logs",
                        to="complaints.complaint",
                    ),
                ),
            ],
            options={
                "verbose_name": "Complaint Status Log",
                "verbose_name_plural": "Complaint Status Logs",
                "ordering": ["changed_at"],
            },
        ),
    ]
