# Generated by Django 5.2.4 on 2026-03-25 17:54

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("analytics", "0001_initial"),
        ("coverages", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QoEReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("DATA", "Mobile Data / Internet"),
                            ("VOICE", "Voice Calls"),
                            ("SMS", "Text Messaging"),
                            ("FIXED", "Fixed Broadband"),
                        ],
                        db_index=True,
                        default="DATA",
                        max_length=10,
                    ),
                ),
                (
                    "connection_type",
                    models.CharField(
                        choices=[
                            ("2G", "2G"),
                            ("3G", "3G"),
                            ("4G", "4G"),
                            ("5G", "5G"),
                        ],
                        db_index=True,
                        help_text="Network technology the user is connected to (3G, 4G, 5G).",
                        max_length=5,
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        help_text="1 = Very Poor, 5 = Excellent",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "download_speed",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Download speed in Mbps.",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "upload_speed",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Upload speed in Mbps.",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "latency_ms",
                    models.PositiveIntegerField(
                        blank=True, help_text="Latency in milliseconds.", null=True
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional description of the network experience.",
                        max_length=1000,
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                (
                    "ip_hash",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="SHA-256 hash of submitter IP for rate limiting.",
                        max_length=64,
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False, help_text="Verified by BOCRA staff."
                    ),
                ),
                (
                    "is_flagged",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Flagged as suspicious (auto or manual).",
                    ),
                ),
                (
                    "district",
                    models.ForeignKey(
                        blank=True,
                        help_text="Resolved from coordinates or selected manually.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="qoe_reports",
                        to="coverages.district",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qoe_reports",
                        to="analytics.networkoperator",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set automatically if user is authenticated.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="qoe_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "QoE Report",
                "verbose_name_plural": "QoE Reports",
                "ordering": ["-submitted_at"],
                "indexes": [
                    models.Index(
                        fields=["operator", "submitted_at"],
                        name="qoe_qoerepo_operato_2b6daa_idx",
                    ),
                    models.Index(
                        fields=["district", "submitted_at"],
                        name="qoe_qoerepo_distric_d878fa_idx",
                    ),
                    models.Index(
                        fields=["rating"], name="qoe_qoerepo_rating_811334_idx"
                    ),
                ],
            },
        ),
    ]
