# Generated by Django 5.2.4 on 2026-03-25 18:19

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("analytics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScorecardWeightConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "dimension",
                    models.CharField(
                        choices=[
                            ("COVERAGE", "Network Coverage"),
                            ("QOE", "Quality of Experience"),
                            ("COMPLAINTS", "Complaint Handling"),
                            ("QOS", "QoS Compliance"),
                        ],
                        db_index=True,
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Weight value between 0 and 1. All weights should sum to 1.0.",
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Explanation of what this dimension measures.",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scorecard_weight_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Scorecard Weight",
                "verbose_name_plural": "Scorecard Weights",
                "ordering": ["dimension"],
            },
        ),
        migrations.CreateModel(
            name="ManualMetricEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "period",
                    models.DateField(
                        db_index=True,
                        help_text="Reporting period (first day of month).",
                    ),
                ),
                (
                    "metric_name",
                    models.CharField(
                        help_text="Name of the metric (e.g. 'Customer Satisfaction Index').",
                        max_length=200,
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=4, help_text="Metric value.", max_digits=12
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        help_text="Unit of measurement (%, score, BWP, etc.).",
                        max_length=50,
                    ),
                ),
                (
                    "entered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="manual_metric_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manual_metrics",
                        to="analytics.networkoperator",
                    ),
                ),
            ],
            options={
                "verbose_name": "Manual Metric Entry",
                "verbose_name_plural": "Manual Metric Entries",
                "ordering": ["-period", "operator__name", "metric_name"],
                "unique_together": {("operator", "period", "metric_name")},
            },
        ),
        migrations.CreateModel(
            name="OperatorScore",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "period",
                    models.DateField(
                        db_index=True,
                        help_text="Reporting period (first day of month).",
                    ),
                ),
                (
                    "coverage_score",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Score based on network coverage percentage (0-100).",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "qoe_score",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Score based on citizen QoE ratings (0-100).",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "complaints_score",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Score based on complaint handling (fewer = higher, 0-100).",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "qos_score",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Score based on QoS benchmark compliance (0-100).",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "composite_score",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Weighted composite of all dimension scores (0-100).",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "rank",
                    models.PositiveSmallIntegerField(
                        help_text="Rank among operators for this period (1 = best)."
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON with raw values and calculation details.",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scorecard_scores",
                        to="analytics.networkoperator",
                    ),
                ),
            ],
            options={
                "verbose_name": "Operator Score",
                "verbose_name_plural": "Operator Scores",
                "ordering": ["-period", "rank"],
                "indexes": [
                    models.Index(
                        fields=["operator", "-period"],
                        name="scorecard_o_operato_c6eb42_idx",
                    )
                ],
                "unique_together": {("operator", "period")},
            },
        ),
    ]
